Change main API to include major_info
sonowz/graduate-adventure pull request #78
Opened 2017-07-18 09:15 UTC by dnsdhrj

Also removed static file serving in backend server, since it's no longer needed.

2017-07-20 01:15 UTC, skystar-p requested changes
review review

2017-07-20 01:15 UTC, skystar-p commented on backend/api/login/tests.py
> +        sugang_list_dir = os.path.join(settings.BASE_DIR, 'test_sample/sugang_list.pickle')
`os.path.join` can take multiple arguments. So `os.path.join(settings.BASE_DIR, 'test_sample', 'sugang_list.pickle')` is right.

2017-07-20 01:25 UTC, skystar-p commented
Can you show us what data is saved in `tables`?

2017-07-20 06:09 UTC, dnsdhrj commented
It is `dict` which will be later converted to `JSON` in #30 main data response. The format is same.

2017-07-22 05:51 UTC, dnsdhrj commented
Also fixed bug in `login/view.py`
```python
request.data['major_info'] is immutable
```

2017-07-22 06:05 UTC, skystar-p approved these changes

2017-07-22 06:06 UTC, merged