Refactor types & Implement loading overlay
sonowz/graduate-adventure pull request #79
Opened 2017-07-19 09:12 UTC by Jhuni0123

- I made `Utils/` directory for our libraries of types and function which is globally used.
- I made `GlobalMsg` to simply communicate between parent and children. Parents catch the global messages from children and perform update.
- Finally I add loading overlay when submit login form. User can know whether the click submit is really working.
![loading](https://user-images.githubusercontent.com/16764073/28359316-b5bfacb8-6cac-11e7-8cc8-204c91871bee.png)

2017-07-20 03:47 UTC, MKRoughDiamond commented on frontend/src/elm/Utils/Major.elm
> +      "주전공(복/부)"
Are there differences between "주전공(단일)" and "주전공(복/부)"? Is "주전공(복/부)" just for simplifying the code?
I think it is enough to show users "주전공". Users can see and count the number of tabs.

2017-07-20 06:21 UTC, sonowz requested changes
In some files, import order is somewhat messy.
I recommend putting global imports first and local module imports later.

2017-07-20 06:21 UTC, dnsdhrj commented on frontend/src/elm/Login/MajorForm/View.elm
>        , div [ id "table-wrapper" ] [ ]
Indent is weird here.

2017-07-20 06:21 UTC, dnsdhrj commented on frontend/src/elm/Login/Msgs.elm
> +  | Global GlobalMsg
I think `None` should be the last to make code neat.

2017-07-21 08:56 UTC, sonowz requested changes

2017-07-21 08:56 UTC, dnsdhrj commented on frontend/src/elm/Login/MajorForm/View.elm
>          ]
Between line 16-17, indentation is 4.
I think line 17-20 has tab inside.

2017-07-21 09:30 UTC, Jhuni0123 commented on frontend/src/elm/Utils/Major.elm
> +      "주전공(복/부)"
Yes there are big differences. Please check http://cse.snu.ac.kr/undergraduate/degree-requirements.
But we can consider changing only "주전공(단일)" to "주전공"

2017-07-21 10:11 UTC, sonowz approved these changes

2017-07-21 10:12 UTC, dnsdhrj commented
Good. Now code looks more clean.

2017-07-21 10:18 UTC, merged