Implement Request Form(WIP)
sonowz/graduate-adventure pull request #91
Opened 2017-07-25 02:53 UTC by MKRoughDiamond

* Content will be added later

2017-08-01 19:11 UTC, MKRoughDiamond commented
now it works!

2017-08-02 13:20 UTC, sonowz requested changes

2017-08-02 13:20 UTC, sonowz commented on frontend/src/elm/Main/Response.elm
> +import Utils.Major as Utils
Importing name is weird. I think it should be
`import Main.Models as Models`
`import Utils.Major as Major`

2017-08-02 13:20 UTC, sonowz commented on frontend/src/elm/Main/Response.elm
> +    ( Json.field "liberal_acq" Json.int )
Would be better if it has newline at the end of file.

2017-08-02 13:20 UTC, dnsdhrj commented on frontend/src/elm/Main/Update.elm
> +import Debug
I think importing orders can be rearranged here.

2017-08-02 13:20 UTC, dnsdhrj commented on frontend/src/elm/Utils/Major.elm
> +stringToTypeNormal input = normalization (stringToType input)
What does `Normal` mean? I think it should be more specific.

2017-08-02 14:36 UTC, Jhuni0123 commented on frontend/src/elm/Main/Response.elm
> +    ( Json.field "liberal_acq" Json.int )
We can use `editorconfig` to force inserting newline at the end of file.

2017-08-02 14:38 UTC, Jhuni0123 commented on frontend/src/elm/Main.elm
> +    commands : Routes.Route -> (Cmd Msg)
`initialCommand` is more better than `commands`

2017-08-02 14:56 UTC, Jhuni0123 commented
I think small commits that fix minor things should be squashed.

2017-08-02 18:50 UTC, MKRoughDiamond commented on frontend/src/elm/Main/Response.elm
> +    ( Json.field "liberal_acq" Json.int )
fixed

2017-08-03 05:10 UTC, skystar-p commented
Is this PR done?

2017-08-03 06:08 UTC, sonowz approved these changes
I'll approve this.

2017-08-03 06:47 UTC, MKRoughDiamond commented
done

2017-08-03 07:01 UTC, merged